### ISSUE TITLE
Microsoft video-playback is broken

### ISSUE THREAD

**Issue by PhymIsBored** [gediminasel/videospeed-firefox#1]
The video does not show video with the addon enabled, sound plays normally.

https://www.microsoft.com/en-us/videoplayer/embed/RWfonD?pid=ocpVideo1-innerdiv-oneplayer&jsapi=true&maskLevel=20&market=en-us

**Comment by gediminasel** [comment]
Hi, thanks for reporting. This is a known issue from the Chrome extension (e.g. https://github.com/igrigorik/videospeed/issues/936). It occurs on sites that use `:first-child` selector to style video because the controller node is inserted before it. It would be best to have an upstream fix in https://github.com/igrigorik/videospeed.
I might implement a workaround: e.g. have a list of domains where the controller should be inserted after the video.

**Comment by gediminasel** [comment]
Hi,
I pushed a workaround. Please update (0.7.4) and let me know if it works and if it breaks something else.

**Comment by PhymIsBored** [comment]
Works for me. Thank you
